---
version: "3.7"
services:
  web:
    image: docker.io/library/nginx:latest
    restart: unless-stopped
    container_name: barrybox
    ports:
      - 8013:80
    volumes:
      - ./web:/code:z
      - ./site.conf:/etc/nginx/conf.d/default.conf:Z

  php:
    container_name: barrybox-php
    image: docker.io/library/php:fpm
    restart: unless-stopped
    volumes:
      - ./web:/code:z
